[project]
name = "ai-patcher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.9"
dependencies = [
    "mido>=1.3.3",
    "pydantic>=2.11.10",
    "python-rtmidi>=1.5.8",
]
